//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_3.Dominio.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;

    public partial class Tarea_3_Ing_b41250Entities1 : DbContext
    {
        public Tarea_3_Ing_b41250Entities1()
            : base("name=Tarea_3_Ing_b41250Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alias> alias { get; set; }
        public virtual DbSet<caracteristicaPersona> caracteristicaPersona { get; set; }
        public virtual DbSet<categoriaDelito> categoriaDelito { get; set; }
        public virtual DbSet<delegacion> delegacion { get; set; }
        public virtual DbSet<delito> delito { get; set; }
        public virtual DbSet<delitoSecundario> delitoSecundario { get; set; }
        public virtual DbSet<expediente> expediente { get; set; }
        public virtual DbSet<hecho> hecho { get; set; }
        public virtual DbSet<imagen> imagen { get; set; }
        public virtual DbSet<lugarHecho> lugarHecho { get; set; }
        public virtual DbSet<objeto> objeto { get; set; }
        public virtual DbSet<oficina> oficina { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<personaJuridica> personaJuridica { get; set; }
        public virtual DbSet<poblacionVulnerable> poblacionVulnerable { get; set; }
        public virtual DbSet<policia> policia { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<subCategoriaDelito> subCategoriaDelito { get; set; }
        public virtual DbSet<subTipoObjeto> subTipoObjeto { get; set; }
        public virtual DbSet<tipoIdentificacion> tipoIdentificacion { get; set; }
        public virtual DbSet<tipoIdVehiculo> tipoIdVehiculo { get; set; }
        public virtual DbSet<tipoObjeto> tipoObjeto { get; set; }
        public virtual DbSet<unidad> unidad { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
